config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    patch'users/:id' => 'devise/registrations#update', :as => 'user_registration'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :teachers
  resources :groups
  resources :audiences
  resources :subjects
  resources :tables do
    resources :schedules
  end
  root 'tables#index'
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :tables
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :find_group, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]
  def index
    @groups = Group.all.sort_by { |e| e.name  }
  end

  def new
    @group = Group.new
  end

  def edit

  end

  def create
    @error = ""
    @group = Group.new(group_params)
    @try = Group.find_by name: @group.name
    if @group.name != ""
      if @try != nil
        @error = "Такая группа уже есть!"
        render 'new'
        return
      end
      if @group.save
        redirect_to groups_path
      else
        render 'new'
      end
    else
      @error = "Поле не может быть пустым!"
      render 'new'
    end
  end

  def update
    if @group.update(group_params)
      redirect_to groups_path
    else
      render 'edit'
    end
  end

  def destroy
    schedules = Schedule.all
    schedules.each do |e|
      if e.group_id == @group.id
        e.destroy
      end
    end
    @table = Table.find_by group_id: @group.id
    if @table != nil
      @table.destroy
    end
    @group.destroy
    redirect_to groups_path
  end

  private
  def group_params
    params.require(:group).permit(:name)
  end

  def find_group
    @group = Group.find(params[:id])
  end

end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/edit.html.erb
<h1>Изменить группу</h1>
    <%= form_for @group do |f| %>
      <p>
        <label>Номер</label><br>
        <%= f.text_field :name %>
      </p>
      <p>
        <%= f.submit "Изменить", {:class=>'btn waves-effect waves-light'} %>
      </p>
    <% end %>

app/views/groups/index.html.erb
<div class="col l7 push-l2 s12">
  <ul class="collection with-header">
      <li class="collection-header"><h4>Группы</h4></li>
      <% @groups.each do |group| %>
        <li class="collection-item">
          <div>
            <%= group.name %>
            <% if current_user.try(:admin?) %>
              <%= link_to group_path(group), method: :delete, data: { confirm: 'Вы уверены?' } do %>
                <b class="secondary-content">
                  <i class="material-icons tooltipped" data-position="top" data-delay="50" data-tooltip="Удалить">delete_sweep</i>
                </b>
              <% end %>

              <%= link_to edit_group_path(group.id) do %>
                <b class="secondary-content">
                  <i class="material-icons tooltipped" data-position="top" data-delay="50" data-tooltip="Изменить">edit</i>
                </b>
              <% end %>
            <% end %>
          </div>
        </li>
      <% end %>
  </ul>
</div>

app/views/groups/new.html.erb
<h3>Новая группа</h3>
<%= if @error != "" then @error else "" end%>
<%= form_for @group do |f| %>
  <p>
    <label>Номер</label><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.submit "Добавить", {:class=>'btn waves-effect waves-light'} %>
  </p>
<% end %>