config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    patch'users/:id' => 'devise/registrations#update', :as => 'user_registration'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :teachers
  resources :groups
  resources :audiences
  resources :subjects
  resources :tables do
    resources :schedules
  end
  root 'tables#index'
end

app/models/audience.rb
class Audience < ApplicationRecord

end

app/controllers/audiences_controller.rb
class AudiencesController < ApplicationController
  before_action :find_audience, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @audiences = Audience.all.sort_by { |e| e.name  }
  end

  def new
    @audience = Audience.new
  end

  def edit

  end

  def show
    @count = 1
    @schedules = Schedule.where(audience_id: @audience.id)
  end

  def create
    @error = ""
    @audience = Audience.new(audience_params)
    @try = Audience.find_by name: @audience.name
    if @audience.name != ""
      if @try != nil
        @error = "Такая аудитория уже есть!"
        render 'new'
        return
      end
      if @audience.save
        redirect_to audiences_path
      else
        render 'new'
      end
    else
      @error = "Поле не может быть пустым!"
      render 'new'
    end
  end

  def update
    if @audience.update(audience_params)
      redirect_to audiences_path
    else
      render 'edit'
    end
  end

  def destroy
    schedules = Schedule.all
    schedules.each do |e|
      if e.audience_id == @audience.id
        e.destroy
      end
    end
    @audience.destroy
    redirect_to audiences_path
  end

  private
  def audience_params
    params.require(:audience).permit(:name)
  end

  def find_audience
    @audience = Audience.find(params[:id])
  end

end

app/helpers/audiences_helper.rb
module AudiencesHelper
end

app/views/audiences/edit.html.erb
<h1>Изменить название аудитории</h1>
    <%= form_for @audience do |f| %>
      <p>
        <label>Название</label><br>
        <%= f.text_field :name %>
      </p>
      <p>
        <%= f.submit "Изменить", {:class=>'btn waves-effect waves-light'} %>
      </p>
    <% end %>

app/views/audiences/index.html.erb
<div class="col l7 push-l2 s12">
  <ul class="collection with-header">
      <li class="collection-header"><h4>Аудитории</h4></li>
      <% @audiences.each do |audience| %>
        <li class="collection-item">
          <div>
            <%= link_to audience_path(audience) do %>
              <%= audience.name %>
            <% end %>
            <% if current_user.try(:admin?) %>
              <%= link_to audience_path(audience), method: :delete, data: { confirm: 'Вы уверены?' } do %>
                <b class="secondary-content">
                  <i class="material-icons tooltipped" data-position="top" data-delay="50" data-tooltip="Удалить">delete_sweep</i>
                </b>
              <% end %>

              <%= link_to edit_audience_path(audience.id) do %>
                <b class="secondary-content">
                  <i class="material-icons tooltipped" data-position="top" data-delay="50" data-tooltip="Изменить">edit</i>
                </b>
              <% end %>
            <% end %>
          </div>
        </li>
      <% end %>
  </ul>
</div>

app/views/audiences/new.html.erb
<h3>Новая аудитория</h3>
<%= if @error != "" then @error else "" end%>
<%= form_for @audience do |f| %>
  <p>
    <label>Название</label><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.submit "Добавить", {:class=>'btn waves-effect waves-light'} %>
  </p>
<% end %>

app/views/audiences/show.html.erb
<div style="overflow: auto;">
<table class="bordered  centered">
       <thead>
         <tr>
             <th data-field="n"></th>
             <th data-field="Понедельник">Понедельник</th>
             <th data-field="Вторник">Вторник</th>
             <th data-field="Среда">Среда</th>
             <th data-field="Четверг">Четверг</th>
             <th data-field="Пятница">Пятница</th>
             <th data-field="Суббота">Суббота</th>
         </tr>
       </thead>
       <tbody>
         <% (0...7).each do |i| %>
           <tr>
             <% (0...7).each do |j| %>
                <% if j == 0 %>
                  <td><%=i + j + 1 %></td>
                <% else %>
                <% finded_schedule = @schedules.find_all{|schedule| schedule.day == j} %>
                <% finded_schedule = finded_schedule.find_all{|schedule| schedule.period == i+1} %>
                <% if finded_schedule != [] %>
                <td>
                  <% element = finded_schedule[0] %>
                  <%= Subject.find(element.subject_id).name %><br>
                  <%= Group.find(element.group_id).name %><br>
                  <%= Teacher.find(element.teacher_id).name %><br>
                  <%= Audience.find(element.audience_id).name %>
                  <% if current_user.try(:admin?) %>
                  <%= link_to 'Удалить', [element.table, element], method: :delete, data: { comfirm: 'Вы уверены?' }%>
                  <% end %>
                </td>
                    <% else %>
                    <td>
                      <br><br><br><br>
                    </td>
                    <% end %>
                <% end %>
                <% @count += 1 %>
             <% end %>
           </tr>
         <% end %>
       </tbody>

     </table>
</div>