config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    patch'users/:id' => 'devise/registrations#update', :as => 'user_registration'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :teachers
  resources :groups
  resources :audiences
  resources :subjects
  resources :tables do
    resources :schedules
  end
  root 'tables#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/audience.rb
class Audience < ApplicationRecord

end

app/models/group.rb
class Group < ApplicationRecord
  has_many :tables
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :table
end

app/models/subject.rb
class Subject < ApplicationRecord

end

app/models/table.rb
class Table < ApplicationRecord
  has_many :schedules
  belongs_to :group
end

app/models/teacher.rb
class Teacher < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/audiences_controller.rb
class AudiencesController < ApplicationController
  before_action :find_audience, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @audiences = Audience.all.sort_by { |e| e.name  }
  end

  def new
    @audience = Audience.new
  end

  def edit

  end

  def show
    @count = 1
    @schedules = Schedule.where(audience_id: @audience.id)
  end

  def create
    @error = ""
    @audience = Audience.new(audience_params)
    @try = Audience.find_by name: @audience.name
    if @audience.name != ""
      if @try != nil
        @error = "Такая аудитория уже есть!"
        render 'new'
        return
      end
      if @audience.save
        redirect_to audiences_path
      else
        render 'new'
      end
    else
      @error = "Поле не может быть пустым!"
      render 'new'
    end
  end

  def update
    if @audience.update(audience_params)
      redirect_to audiences_path
    else
      render 'edit'
    end
  end

  def destroy
    schedules = Schedule.all
    schedules.each do |e|
      if e.audience_id == @audience.id
        e.destroy
      end
    end
    @audience.destroy
    redirect_to audiences_path
  end

  private
  def audience_params
    params.require(:audience).permit(:name)
  end

  def find_audience
    @audience = Audience.find(params[:id])
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :find_group, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]
  def index
    @groups = Group.all.sort_by { |e| e.name  }
  end

  def new
    @group = Group.new
  end

  def edit

  end

  def create
    @error = ""
    @group = Group.new(group_params)
    @try = Group.find_by name: @group.name
    if @group.name != ""
      if @try != nil
        @error = "Такая группа уже есть!"
        render 'new'
        return
      end
      if @group.save
        redirect_to groups_path
      else
        render 'new'
      end
    else
      @error = "Поле не может быть пустым!"
      render 'new'
    end
  end

  def update
    if @group.update(group_params)
      redirect_to groups_path
    else
      render 'edit'
    end
  end

  def destroy
    schedules = Schedule.all
    schedules.each do |e|
      if e.group_id == @group.id
        e.destroy
      end
    end
    @table = Table.find_by group_id: @group.id
    if @table != nil
      @table.destroy
    end
    @group.destroy
    redirect_to groups_path
  end

  private
  def group_params
    params.require(:group).permit(:name)
  end

  def find_group
    @group = Group.find(params[:id])
  end

end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :find_subject, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @subjects = Subject.all.sort_by { |e| e.name  }
  end

  def new
    @subject = Subject.new
  end

  def edit

  end

  def show
    @count = 1
    @schedules = Schedule.where(subject_id: @subject.id)
  end

  def create
    @error = ""
    @subject = Subject.new(subject_params)
    @try = Subject.find_by name: @subject.name
    if @subject.name != ""
      if @try != nil
        @error = "Такой предмет уже есть!"
        render 'new'
        return
      end
      if @subject.save
        redirect_to subjects_path
      else
        render 'new'
      end
    else
      @error = "Поле не может быть пустым!"
      render 'new'
    end
  end

  def update
    if @subject.update(subject_params)
      redirect_to subjects_path
    else
      render 'edit'
    end
  end

  def destroy
    schedules = Schedule.all
    schedules.each do |e|
      if e.subject_id == @subject.id
        e.destroy
      end
    end
    @subject.destroy
    redirect_to subjects_path
  end

  private
  def subject_params
    params.require(:subject).permit(:name)
  end

  def find_subject
    @subject = Subject.find(params[:id])
  end

end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  before_action :find_table, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  def index
    temp_tables = []
    Table.all.each do |e|
      temp = []
      temp << e
      temp << Group.all.find{|g| g.id == e.group_id}.name
      temp_tables << temp
    end
    @tables = temp_tables.sort_by{|e| e[1]}
  end

  def new
    @table = Table.new
    @groups = Group.all.sort_by { |e| e.name  }
  end

  def show
    @count = 1
    @table = find_table
    @schedules = Schedule.where(table_id: @table)
    if current_user.try(:admin?)
      @group = @table.group_id
      @subjects = Subject.all.sort_by { |e| e.name  }
      @audiences = Audience.all.sort_by { |e| e.name  }
      @teachers = Teacher.all.sort_by { |e| e.name  }
    end
  end

  def create
      @table = Table.new(table_params)
      if @table.save
        redirect_to tables_path
      else
        render 'new'
      end
  end

  def destroy
    @table.destroy
    redirect_to tables_path
  end

  private
  def table_params
    params.require(:table).permit(:group_id)
  end

  def schedule_params
    params.require(:schedule).permit(:day, :periond, 0, 0, 0, 0, 0)
  end

  def find_table
    @table = Table.find(params[:id])
  end

end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :find_teacher, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @teachers = Teacher.all.sort_by { |e| e.name  }
  end

  def new
    @teacher = Teacher.new
  end

  def edit

  end

  def show
    @count = 1
    @schedules = Schedule.where(teacher_id: @teacher.id)
  end

  def create
      @error = ""
      @teacher = Teacher.new(teacher_params)
      @try = Teacher.find_by name: @teacher.name
      if @teacher.name != ""
        if @try != nil
          @error = "Такой преподаватель уже есть!"
          render 'new'
          return
        end
        if @teacher.save
          redirect_to teachers_path
        else
          render 'new'
        end
      else
        @error = "Поле не может быть пустым!"
        render 'new'
      end
  end

  def update
    if @teacher.update(teacher_params)
        redirect_to teachers_path
    else
      render 'edit'
    end
  end

  def destroy
    schedules = Schedule.all
    schedules.each do |e|
      if e.teacher_id == @teacher.id
        e.destroy
      end
    end
    @teacher.destroy
    redirect_to teachers_path
  end

  private
  def teacher_params
    params.require(:teacher).permit(:name)
  end

  def find_teacher
    @teacher = Teacher.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/audiences_helper.rb
module AudiencesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Timetable</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="theme-color" content="#009688"
    <!--Import Google Icon Font-->
    <%= stylesheet_link_tag "application", 'https://fonts.googleapis.com/css?family=Material+Icons', :media => "all" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="teal">
   <div class="nav-wrapper container">
     <a href="/" class="brand-logo">Расписание</a>
     <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
     <ul class="right hide-on-med-and-down">
       <li><%=link_to 'Расписания', tables_path %></li>
       <li><%=link_to 'Преподаватели', teachers_path %></li>
       <li><%=link_to 'Аудитории', audiences_path %></li>
       <li><%=link_to 'Группы', groups_path %></li>
       <li><%=link_to 'Предметы', subjects_path %></li>
       <% if current_user.try(:admin?) %>
         <li><%=link_to 'Выйти', destroy_user_session_path, method: :delete, data: { confirm: 'Вы уверены?' } %></li>
         <% else %>
         <li><%=link_to 'Войти', new_user_session_path %></li>
       <% end %>
     </ul>
   </div>
   <ul class="side-nav" id="mobile-demo">
     <% if current_user.try(:admin?) %>
       <li><%=link_to 'Выйти', destroy_user_session_path, method: :delete, data: { confirm: 'Вы уверены?' } %></li>
       <% else %>
       <li><%=link_to 'Войти', new_user_session_path %></li>
     <% end %>
     <li><%=link_to 'Расписания', tables_path %></li>
     <li><%=link_to 'Преподаватели', teachers_path %></li>
     <li><%=link_to 'Аудитории', audiences_path %></li>
     <li><%=link_to 'Группы', groups_path %></li>
     <li><%=link_to 'Предметы', subjects_path %></li>
    </ul>
 </nav>
 <div class="container">
   <p class="alert"><%= alert %></p>

  <div class="row">
    <%= yield %>
  </div>
    <% if current_user.try(:admin?) %>
    <div class="fixed-action-btn click-to-toggle">
    <a class="btn-floating btn-large red">
      <i class="material-icons">menu</i>
    </a>
    <ul>
      <li>
        <%=link_to(new_teacher_path) do %>
          <b class="btn-floating red tooltipped" data-position="left" data-delay="50" data-tooltip="Добавить преподавателя"><i class="material-icons">perm_identity</i></b>
        <% end %>
      </li>
      <li>
        <%=link_to(new_subject_path) do %>
          <b class="btn-floating yellow darken-2 tooltipped" data-position="left" data-delay="50" data-tooltip="Добавить предмет"><i class="material-icons">book</i></b>
        <% end %>
      </li>
      <li>
        <%=link_to(new_audience_path) do %>
          <b class="btn-floating green tooltipped" data-position="left" data-delay="50" data-tooltip="Добавить аудиторию"><i class="material-icons">weekend</i></b>
        <% end %>
      </li>
      <li>
        <%=link_to(new_group_path) do %>
          <b class="btn-floating blue tooltipped" data-position="left" data-delay="50" data-tooltip="Добавить группу"><i class="material-icons">supervisor_account</i></b>
        <% end %>
      </li>
      <li>
        <%=link_to(new_table_path) do %>
          <b class="btn-floating deep-purple tooltipped" data-position="left" data-delay="50" data-tooltip="Добавить расписание"><i class="material-icons">library_add</i></b>
        <% end %>
      </li>
    </ul>
  </div>
  <% end %>
</div>
<script type="text/javascript">
  text = '<%= notice %>';
  window.onload = MakeToast(text);
</script>
  </body>
</html>